### ISSUE TITLE
Cannot press buttons very fast

### ISSUE THREAD

**Issue by kndoshn** [getditto/demoapp-inventory#26]
# What is this?
- @mbalex99 has reported that the counter value change doesn't happen when he presses buttons very fast.
- It became slower in the process of the refactoring (private repo):
  - https://github.com/getditto/demo-apps/pull/432

# Where is the problem?

### Before the refactoring:
- After the live query callback catches value changes, the table view cell's methods will be called to update the values:
```swift
cell.updateItemCount(count: newCount)
cell.animateBackground()
```
- This was possible because the view controller used to be observing the live query directly, instead of using the Ditto manager design pattern, so it knows the `newCount` value that shows what the new value in the Ditto Document is.
  - We decided not to handle Ditto events in view controllers directly and separate view code and ditto code.

### Current code:
- After the live query callback catches value changes, the table view's delegate method is triggered by `reloadRows(at:)`:
```swift
tableView.reloadRows(at: indexPaths, with: .automatic)
```
- This way is slower because the `tableView cellForRowAt` delegate method won't be called instantly after `reloadRows(at:)`.

# How to fix it?
- The new counter values are not being passed to the view controller directly now.
  - Should we pass them through the current Passthrough object?
  - Should we observe the live query in the view controller and receives the callback events directly, so that the view controller has all the information about updates?

**Comment by okdistribute** [comment]
@mbalex99 fixed this on a new version of this app that uses SwiftUI. Do we want to use that app instead of this old UIKit one?
